#!/usr/bin/env python3
"""Scan images/ and write images-manifest.js for the gallery."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
IMG_DIR = ROOT / "images"
EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic", ".heif"}


def main() -> None:
    if not IMG_DIR.is_dir():
        print(f"No folder at {IMG_DIR}")
        return
    paths: list[str] = []
    for p in sorted(IMG_DIR.iterdir(), key=lambda x: x.name.lower()):
        if p.is_file() and p.suffix.lower() in EXT:
            paths.append(f"images/{p.name}")
    out = ROOT / "images-manifest.js"
    out.write_text(
        "// Generated by update-manifest.py — run after adding/removing files in images/\n"
        "window.BOOK_GALLERY_STATIC_IMAGES = "
        + json.dumps(paths, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(paths)} image paths to {out.name}")


if __name__ == "__main__":
    main()
